name: Dev Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/dev_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@main
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies Build
        run: yarn

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheatgui-dev-b${{ github.run_number }}
          path: dist/
